export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_FAIL = 'FETCH_SERVICES_FAIL';
export const SELECT_SERVICE = 'SELECT_SERVICE';
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const FETCH_USER_SERVICES_REQUEST = 'FETCH_USER_SERVICES_REQUEST';
export const FETCH_USER_SERVICES_SUCCESS = 'FETCH_USER_SERVICES_SUCCESS';
export const FETCH_USER_SERVICES_FAIL = 'FETCH_USER_SERVICES_FAIL';
