export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_FAIL = 'FETCH_SERVICES_FAIL';

export const SELECT_SERVICE = 'SELECT_SERVICE';

export const SET_AUTH_USER = 'SET_AUTH_USER';

export const FETCH_USER_SERVICES_REQUEST = 'FETCH_USER_SERVICES_REQUEST';
export const FETCH_USER_SERVICES_SUCCESS = 'FETCH_USER_SERVICES_SUCCESS';
export const FETCH_USER_SERVICES_FAIL = 'FETCH_USER_SERVICES_FAIL';

export const FETCH_SERVICE_REQUEST = 'FETCH_SERVICE_REQUEST';
export const FETCH_SERVICE_SUCCESS = 'FETCH_SERVICE_SUCCESS';
export const FETCH_SERVICE_FAIL = 'FETCH_SERVICE_FAIL';

export const FETCH_OFFER_REQUEST = 'FETCH_OFFER_REQUEST';
export const FETCH_SENT_OFFER_SUCCESS = 'FETCH_SENT_OFFER_SUCCESS';
export const FETCH_RECEIVED_OFFER_SUCCESS = 'FETCH_RECEIVED_OFFER_SUCCESS';
export const FETCH_OFFER_FAIL = 'FETCH_OFFER_FAIL';

export const CHANGE_OFFER_STATUS = 'CHANGE_OFFER_STATUS';

export const COLLABORATION_CREATED_FROM_OFFER =
  'COLLABORATION_CREATED_FROM_OFFER';

export const FETCH_USER_MESSAGES_REQUEST = 'FETCH_USER_MESSAGES_REQUEST';
export const FETCH_USER_MESSAGES_SUCCESS = 'FETCH_USER_MESSAGES_SUCCESS';
export const FETCH_USER_MESSAGES_FAIL = 'FETCH_USER_MESSAGES_FAIL';
